<?php

namespace FunPro\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findUserByUsername(array $usernames)
    {
        $qb = $this->createQueryBuilder('u');

        return $qb->where($qb->expr()->in('u.username', ':usernames'))
            ->setParameter('usernames', $usernames)
            ->getQuery()
            ->getResult(Query::HYDRATE_ARRAY);
    }
}
