chat_public:
    channel: chat/public
    handler:
        callback: 'chat.public' #related to the getName() of your topic
game_room:
    channel: game/room/{room}
    handler:
        callback: 'game.topic' #related to the getName() of your topic
game_rpc:
    channel: game/{method}
    handler:
        callback: 'game' #related to the getName() or your RPC service
    requirements:
        method:
            pattern: "[a-z_]+" #accept all valid regex, don't put delimiters !