# Web Socket Configuration
gos_web_socket:
    server:
        port: 8080        #The port the socket server will listen on
        host: dirtyseven.ir   #The host ip to bind to
        router:
            resources:
                - "@FunProUserBundle/Resources/config/pubsub.yml"
                - "@FunProCoreBundle/Resources/config/pubsub.yml"
                - "@FunProSevenBundle/Resources/config/pubsub.yml"
    client:
        firewall: main
        session_handler: "@snc_redis.session.handler"