fun_pro_home_res:
    resource: "@FunProHomeBundle/Resources/config/routing.yml"
    type:     rest

fun_pro_user_res:
    resource: "@FunProUserBundle/Resources/config/routing.yml"
    prefix:   "/user"

oauth_yahoo_login:
    path:     /connect/check-yahoo

oauth_google_login:
    path:     /connect/check-google

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"