vich_uploader:
    db_driver: orm

    mappings:
        avatar:
            uri_prefix:         /avatar
            upload_destination: '%kernel.root_dir%/../web/avatars'
            namer:              vich_uploader.namer_uniqid