services:
    fun_pro.user.oauth_provider:
        class:     FunPro\UserBundle\Security\Core\OAuth\UserProvider
        parent:    hwi_oauth.user.provider.fosub_bridge

    fun_pro_user.chat.public:
        class: FunPro\UserBundle\Topic\PublicTopic
        arguments: ["@gos_web_socket.wamp.topic_manager", "@gos_web_socket.websocket.client_manipulator", "@snc_redis.default"]
        tags:
            - { name: gos_web_socket.topic }

    fun_pro_user.user_rpc:
        class: FunPro\UserBundle\RPC\UserService
        arguments:
            - "@gos_web_socket.wamp.topic_manager"
            - "@gos_web_socket.websocket.client_manipulator"
            - "@snc_redis.default"
            - "@doctrine"
        tags:
            - { name: gos_web_socket.rpc }

    fun_pro_user.friend_rpc:
        class: FunPro\UserBundle\RPC\FriendService
        arguments:
            - "@gos_web_socket.wamp.topic_manager"
            - "@gos_web_socket.websocket.client_manipulator"
            - "@snc_redis.default"
            - "@doctrine"
            - "@fun_pro_user.friend"
            - "@fun_pro_user.blacklist"
        tags:
            - { name: gos_web_socket.rpc }

    fun_pro_user.friend:
        class: FunPro\UserBundle\Persistence\Friend
        arguments: ["@snc_redis.default", "@doctrine"]

    fun_pro_user.blacklist:
        class: FunPro\UserBundle\Persistence\Blacklist
        arguments: ["@snc_redis.default", "@doctrine"]